version: "3"
services:
  story-teller:
    image: childrens-story 
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY} 
    ports:
      - 8081:3000
    restart: always
