name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Build-And-Deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Stop
        run: docker-compose down

      - name: Fix env:
        run : |
          touch .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_KEY }} >> .env  

      - name: Rebuild and run detached
        run: docker-compose up --build -d
